[book]
title = "ğŸˆâ€â¬› snowzxlä¸ªäººåšå®¢ ğŸˆâ€â¬›"
authors = ["snowzxl"]
language = "en"
description = "Personal blog"

[output.html]
git-repository-url = "https://github.com/snowzxl/blog"
git-repository-icon = "fa-github"
